### ISSUE TITLE
every request should not share same kernel

### ISSUE THREAD

**Issue by LinboLen** [TeknooSoftware/symfony-reactphp-bridge#1]
every request should not share same kernel. kernel will be cloned, reference to symfony phpunit, every request should call createClient, and it boot kernel for every request.

same kernel means same service container, and some service behave difference with session, request data, etc.

add following code to RequestBridge
```php
   private function bootKernel() {
        $this->kernel = clone $this->kernel;
        $this->kernel->boot();
    }
```
add `$this->bootKernel();` in RequestBridge __invoke method

**Comment by LinboLen** [comment]
same kernel is closed to the concept of node.js. so i am really confused right now

**Comment by frenchcomp** [comment]
Hi,
Sorry, I missed to write the "__clone" method into the RequestBridge.
The RequestBridge is cloned by RequestListener at each request, but I missed the __clone() method and so the kernel is not cloned. (By default in PHP, objects as attributes are not cloned with the owning object).

**Comment by LinboLen** [comment]
fine, `$bridge = clone $this->bridge;` is what i missed
