### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by aescarcha** [TeknooSoftware/symfony-reactphp-bridge#3]
Hi, could you please update the example from README.MD ? I'm getting this error:

`PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Teknoo\ReactPHPBundle\Bridge\RequestBridge::__construct(), 1 passed in /web/reactWithBundle.php on line 22 and exactly 4 expected in /vendor/teknoo/reactphp-symfony/src/Bridge/RequestBridge.php:92`

Thanks!

**Comment by frenchcomp** [comment]
Hi,
Sorry, I'm doing some houseworks, I had not Internet this week end. I look your issue today.

**Comment by frenchcomp** [comment]
Hi, i have updated the readme, but I invite you to use the Symfony cli described in the Readme instead of a manual php script.
Best,
Richard
